version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.11.4-management-alpine
    container_name: 'rabbitmq'
    hostname: microservices_march
    depends_on:
      - load_balancer
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbit-data:/var/lib/rabbitmq/
        - rabbit-log:/var/log/rabbitmq/
    networks:
        - mm_2023
  load_balancer:
    image: nginx:1.23
    volumes:
      - ./load_balancer/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    networks:
        - mm_2023
        

volumes:
  rabbit-data:
  rabbit-log:

networks:
  mm_2023:
    name: mm_2023
    driver: bridge
