name: create-resources
on: [workflow_dispatch]
jobs:
  create-environment:
     runs-on: ubuntu-22.04
     steps:
       - name: Check out the codebase
         uses: actions/checkout@v3

       - name: Log in to Azure
         uses: azure/login@v1
         with:
           creds: ${{ secrets.AZURE_CREDENTIALS }}

       - name: Create resources
         uses: azure/arm-deploy@v1
         with:
           subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
           resourceGroupName: ${{ secrets.AZURE_RG }}
           template: ${{ github.workspace }}/config/main.bicep
           parameters: 'namePrefix=${{ secrets.AZURE_PREFIX }}'
           failOnStdErr: false
